version: '3.8'
services:
   web:
       build: .
       command: bash -c "spark-submit src/train.py -t spark-submit && python src/train.py -t test && python -m pytest tests"
       ports:
           - 8000:8000
       image: zeroyal/mle.hw1:latest